### ISSUE TITLE
compose-desktop throws koin Exception (but starts anyway)

### ISSUE THREAD

**Issue by mreichelt** [joreilly/PeopleInSpace#24]
Stacktrace:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: A KoinContext is already started
	at org.koin.core.context.KoinContextHandler$register$1.invoke(KoinContextHandler.kt:58)
	at org.koin.core.context.KoinContextHandler$register$1.invoke(KoinContextHandler.kt:26)
	at org.koin.core.state.DefaultJvmThreading.mainOrSynchronized(MainIsolatedStateJVM.kt:41)
	at org.koin.mp.PlatformJvmKt.mpsynchronized(PlatformJvm.kt:27)
	at org.koin.core.context.KoinContextHandler.register(KoinContextHandler.kt:56)
	at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:36)
	at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35)
	at com.surrus.common.di.KoinKt.initKoin(Koin.kt:17)
	at com.surrus.common.di.KoinKt.initKoin$default(Koin.kt:16)
	at MainKt$main$1.invoke(main.kt:36)
	at MainKt$main$1.invoke(main.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.desktop.AppWindowKt$Window$1$1.invoke(AppWindow.kt:83)
	at androidx.compose.desktop.AppWindowKt$Window$1$1.invoke(AppWindow.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.desktop.AppWindow$show$1.invoke(AppWindow.kt:347)
	at androidx.compose.desktop.AppWindow$show$1.invoke(AppWindow.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:187)
	at androidx.compose.desktop.AppWindow$onCreate$1.invoke(AppWindow.kt:326)
	at androidx.compose.desktop.AppWindow$onCreate$1.invoke(AppWindow.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.platform.DesktopSelectionKt$DesktopSelectionContainer$4$1.invoke(DesktopSelection.kt:123)
	at androidx.compose.ui.platform.DesktopSelectionKt$DesktopSelectionContainer$4$1.invoke(DesktopSelection.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.layout.LayoutKt.Layout(Layout.kt:682)
	at androidx.compose.ui.platform.DesktopSelectionKt.Wrap(DesktopSelection.kt:38)
	at androidx.compose.ui.platform.DesktopSelectionKt.access$Wrap(DesktopSelection.kt)
	at androidx.compose.ui.platform.DesktopSelectionKt$DesktopSelectionContainer$4.invoke(DesktopSelection.kt:122)
	at androidx.compose.ui.platform.DesktopSelectionKt$DesktopSelectionContainer$4.invoke(DesktopSelection.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:187)
	at androidx.compose.ui.platform.DesktopSelectionKt.DesktopSelectionContainer(DesktopSelection.kt:121)
	at androidx.compose.ui.platform.DesktopSelectionKt.DesktopSelectionContainer(DesktopSelection.kt:62)
	at androidx.compose.ui.platform.WrapperKt$setContent$1$1.invoke(Wrapper.kt:36)
	at androidx.compose.ui.platform.WrapperKt$setContent$1$1.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:187)
	at androidx.compose.ui.platform.AmbientsKt.ProvideCommonAmbients(Ambients.kt:303)
	at androidx.compose.ui.platform.AmbientsKt$ProvideCommonAmbients$1.invoke(Ambients.kt)
	at androidx.compose.ui.platform.AmbientsKt$ProvideCommonAmbients$1.invoke(Ambients.kt)
	at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:286)
	at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1696)
	at androidx.compose.runtime.Composer.skipCurrentGroup(Composer.kt:1953)
	at androidx.compose.runtime.Composer.recompose(Composer.kt:2083)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:375)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt)
	at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$2$4.invoke(Recomposer.kt:310)
	at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$2$4.invoke(Recomposer.kt)
	at androidx.compose.runtime.dispatch.ActualDesktopKt$DefaultMonotonicFrameClock$2$1.withFrameNanos(ActualDesktop.kt:38)
	at androidx.compose.runtime.dispatch.ActualDesktopKt$DefaultMonotonicFrameClock$2$1$withFrameNanos$1.invokeSuspend(ActualDesktop.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:228)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:167)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:372)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:406)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:398)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:494)
	at kotlinx.coroutines.swing.SwingDispatcher$scheduleResumeAfterDelay$timer$1.actionPerformed(SwingDispatcher.kt:33)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by mreichelt** [comment]
It works again - yay! :)

![Bildschirmfoto 2020-12-15 um 15 43 41](https://user-images.githubusercontent.com/400322/102231642-77530480-3eee-11eb-974d-8d0ab0ce843f.png)
